### PR TITLE
Assert accountNumber in forms

### LINKED ISSUE #12: Hard to debug error case: multisig account has no accountNumber
The multisig account needs an account number on chain at compose time as shown in this example: https://github.com/cosmos/cosmjs/blob/v0.27.0/packages/stargate/src/multisignature.spec.ts#L177-L207

Now if I create a transaction for a newly created multisig address, there will be no account number and

```
    if (!accountOnChain) {
      accountOnChain = {};
    }
    accountOnChain.pubkey = pubkey;
```

will be used from now on. However, due to the missing accountNumber, signing will fail later on with some hard to debug error message:

> Error creating signature: TypeError: Cannot read properties of undefined (reading 'toString') at makeSignDoc (signdoc.js?0bac:31:1)

I think it would make sense to not allow composing a transaction without an accountNumber.

### PR DESCRIPTION
**Pull request by abefernan**
Closes #12

### CODE REVIEW

File: pages/multi/[address]/index.tsx [hunk 1]
```diff
@@ -158,36 +158,44 @@ const Multipage = () => {
...
+                    <Button
+                      label="Claim Rewards"
+                      onClick={() => {
+                        setTxView("claimRewards");
+                      }}
+                    />
+                  </>
+                ) : (
+                  <p>
+                    An account needs to be present on the multisig before creating a transaction.
```
Comment (webmaster128) [inline pages/multi/[address]/index.tsx:196]:
```suggestion
                    An account needs to be present on chain before creating a transaction. Send some tokens to the address first.
```

**Review by webmaster128 — COMMENTED** [review]
Nice. Just a bit more guidance in the error message to be nice to users.
