### PR TITLE
Validate macrocoin, allow empty funds and IBC

### LINKED ISSUE #180: Delegation amount keeps resetting to 0
gm frens! currently unable to delegate ATOM because after clicking 'Create Transaction', the Amount gets reset to 0.

Here's a screen recording encountering the bug:

https://github.com/cosmos/cosmos-multisig-ui/assets/26232238/7bc13eaf-bd4d-4849-baf3-a39410f2433b

### LINKED ISSUE #183: Bug - Bank send does not support big decimals.
Bug:
Using messages of type Bank  send fails with custom denoms when the decimals are big (18 decimals) shows and stores 0 Amount.
I suspect this Number(amount) conversion to make that fail. Maybe use BigInt here?
```
if (!amount || Number(amount) <= 0) {
        setAmountError("Amount must be greater than 0");
        return false;
}
```

I tried to send some IBCed $ARCH that have 18 decimals. trying to send 10000 $ARCH so 10000000000000000000000 prepares a tx that tries to send 0 $ARCH

### LINKED ISSUE #191: Execute Messages will always try to send a denom
So even in cases where you don't need to send coins on an `ExecuteMsg`, the tool will try sending "0" coins, which will fail at the sdk level.

Sending no coins shouldn't default to 0, but an empty vector.

### LINKED ISSUE #192: Custom denoms amount field doesn't work
In case there's a denom not listen in the denom dropdown menu, which is the case for IBC tokens, the amount field is not read properly when creating the transaction.

Whatever number of the custom denom you intent to send, when creating the transaction it is set to zero, which effectively prevents you to sending the denom you intended to send.

### PR DESCRIPTION
**Pull request by abefernan**
Closes #180.
Closes #183.
Closes #191.
Closes #192.

#180 was because of missing validation.
#183 and #192 because we didn't account for IBC tokens not disclosed on the chain-registry.
#191 because if funds/amount was an array, we sent an empty coin instead of an empty array.

### CODE REVIEW

File: components/forms/CreateTxForm/MsgForm/MsgExecuteContractForm.tsx [hunk 1]
```diff
@@ -113,9 +130,11 @@ const MsgExecuteContractForm = ({
       sender: fromAddress,
       contract: contractAddress,
       msg: msgContentUtf8Array,
-      funds: [microCoin],
+      funds: microCoin ? [microCoin] : [],
     });
 
+    console.log({ msgValue });
```
Comment (webmaster128) [inline components/forms/CreateTxForm/MsgForm/MsgExecuteContractForm.tsx:136]: Should we remove this?

File: components/forms/CreateTxForm/MsgForm/MsgInstantiateContractForm.tsx [hunk 2]
```diff
@@ -102,6 +107,13 @@ const MsgInstantiateContractForm = ({
         return false;
       }
 
+      try {
+        macroCoinToMicroCoin({ denom, amount }, chain.assets);
```
Comment (webmaster128) [inline components/forms/CreateTxForm/MsgForm/MsgInstantiateContractForm.tsx:111]: I'm confused by the name of this function because the case in https://github.com/cosmos/cosmos-multisig-ui/issues/183 shows we have a base denom in [atto](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes). 

Should this be renamed to `displayCoinToBaseCoin` or similar?

Comment (abefernan) [reply components/forms/CreateTxForm/MsgForm/MsgInstantiateContractForm.tsx:111]: Yeah the implementation has exceeded the logic behind the initial name I gave it

**Review by webmaster128 — APPROVED** [review]
