### PR TITLE
Get good rpc from array

### LINKED ISSUE #44: Iterate between available endpoints if RPC node is not available
Using Comdex as an example, the console printed an error that the the node was not available. I would suggest putting all RPC endpoints in an array, catching any error, and iterating over the list until there is a successful connection.

On failure at end of array, inform the user that none of the listed RPC endpoints are, available instead of the generic "failed to fetch" message.

### PR DESCRIPTION
**Pull request by abefernan**
Closes #44

### CODE REVIEW

File: components/chainSelect/ChainSelect.tsx [hunk 1]
```diff
@@ -175,13 +171,26 @@ const ChainSelect = () => {
     return "";
   };
 
-  const getNodeFromArray = (nodeArray: { address: string; provider: string }[]) => {
+  const getNodeFromArray = async (nodeArray: { address: string; provider: string }[]) => {
     // only return https connections
-    const secureNodes = nodeArray.filter((node) => node.address.includes("https://"));
+    const secureNodes = nodeArray
+      .filter((node) => node.address.includes("https://"))
```
Comment (webmaster128) [inline components/chainSelect/ChainSelect.tsx:177]:
```suggestion
      .filter((node) => node.address.startsWith("https://"))
```

File: components/chainSelect/ChainSelect.tsx [hunk 2]
```diff
@@ -175,13 +171,26 @@ const ChainSelect = () => {
...
-    return secureNodes[0].address;
+
+    try {
+      for (const node of secureNodes) {
+        // test client connection
+        const client = await StargateClient.connect(node);
+        await client.getHeight();
+        return node;
+      }
+    } catch {}
```
Comment (webmaster128) [inline components/chainSelect/ChainSelect.tsx:191]: Here you need to try/catch inside of the loop. Otherwise the first exception will be handled here and lead to "No RPC nodes available for this chain"

**Review by webmaster128 — APPROVED** [review]
