### PR TITLE
Show connect errors

### LINKED ISSUE #9: Show error to the user when Keplr is missing
The "enable err:" in

```js
  connectWallet = async () => {
    try {
      await window.keplr.enable(process.env.NEXT_PUBLIC_CHAIN_ID);
      const walletAccount = await window.keplr.getKey(
        process.env.NEXT_PUBLIC_CHAIN_ID
      );
      const hasSigned = this.props.signatures.some(
        (sig) => sig.address === walletAccount.bech32Address
      );
      this.setState({ walletAccount, hasSigned });
    } catch (e) {
      console.log("enable err: ", e);
    }
  };
```

happens when Keplr is not installed. It would be nice to propagate that error to the user.

### LINKED ISSUE #78: Tool fails silently when clicking Connect Ledger but Cosmos app is not open
On the tx signing screen when you click "Connect Ledger (WebUSB)" and the Ledger is connected but the Cosmos app is not open, there is an error

> Uncaught (in promise) Error: Please close BOLOS and open the Cosmos Ledger app on your Ledger device.

But this is not shown to the user. Instead nothing happens.

### PR DESCRIPTION
**Pull request by abefernan**
Closes #9.
Closes #78.

Other connecting related errors have been added and it's now easier to add new ones

### CODE REVIEW

File: lib/errorHelpers.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+const getConnectError = (error: unknown): string => {
+  const rawErrorMsg =
+    error instanceof Error ? error.message.toLowerCase() : String(error).toLowerCase();
```
Comment (webmaster128) [inline lib/errorHelpers.ts:3]: Is `String(error)` the same as `error.toString()`?

File: lib/errorHelpers.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
+  // Keplr
+  if (rawErrorMsg.includes("window.keplr is undefined")) {
+    return "Keplr needs to be installed";
+  }
+
+  // Ledger
+  if (rawErrorMsg.includes("navigator.usb is undefined")) {
+    return "Your browser is not compatible with ledger";
```
Comment (webmaster128) [inline lib/errorHelpers.ts:12]:
```suggestion
    return "Your browser is not compatible with Ledger due to missing WebUSB";
```

File: lib/errorHelpers.ts [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+  }
+
+  if (rawErrorMsg.includes("no device selected")) {
+    return "A ledger device needs to be selected";
```
Comment (webmaster128) [inline lib/errorHelpers.ts:16]:
```suggestion
    return "A Ledger device needs to be selected";
```

File: components/forms/TransactionSigning.tsx [hunk 4]
```diff
@@ -67,8 +69,11 @@ const TransactionSigning = (props: Props) => {
       }
 
       setWalletType("Keplr");
+      setConnectError("");
     } catch (e) {
-      console.log("enable keplr err: ", e);
+      const error = getConnectError(e);
+      console.error(error);
```
Comment (webmaster128) [inline components/forms/TransactionSigning.tsx:75]: Don't we want to log `e` which contains the full error information?

File: components/forms/TransactionSigning.tsx [hunk 5]
```diff
@@ -112,8 +117,11 @@ const TransactionSigning = (props: Props) => {
 
       setLedgerSigner(offlineSigner);
       setWalletType("Ledger");
+      setConnectError("");
     } catch (e) {
-      console.log("enable ledger err: ", e);
+      const error = getConnectError(e);
+      console.error(error);
```
Comment (webmaster128) [inline components/forms/TransactionSigning.tsx:123]: Don't we want to log `e` which contains the full error information?

**Review by webmaster128 — COMMENTED** [review]
Nice

File: lib/errorHelpers.ts (hunk 1 above)
Comment (abefernan) [reply lib/errorHelpers.ts:3]: `toString()` is not available (at least from TS point of view) since that `error` is type `unknown`. I tested that `String()` works for these errors and I think every type can be safely cast this way

Comment (webmaster128) [reply lib/errorHelpers.ts:3]: okay cool, thanks

**Review by webmaster128 — APPROVED** [review]
